package com;

import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class ReadScriptGenerate {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String inputFoler = "C:\\TestcaseUtility\\input";
		String outputFolder = "C:\\TestcaseUtility\\output\\";
		System.out.println("============================================================================");
		String s = null;
		String y = new String();		
		s.compareTo(y);
		
		try {
			File folder = new File(inputFoler);
			File[] listOfFiles = folder.listFiles();

			for (File file : listOfFiles) {
				if (file.isFile()) {
					// System.out.println(file.getName());
					System.out.println("START READING FILE :" + inputFoler + file.getName());
					FileReader fr = new FileReader(file); // reads the file
					BufferedReader br = new BufferedReader(fr); // creates a buffering character input stream
					// StringBuffer sb = new StringBuffer(); // constructs a string buffer with no
					// characters
					String line = null;
					ArrayList<StepObject> objStepObjectList = new ArrayList<StepObject>();
					StepObject objStepObject;
					Integer stepNum = 1;
					while ((line = br.readLine()) != null) {
						// sb.append(line); // appends line to string buffer
						line = line.trim();
						// System.out.println(line);
						if (line.startsWith("//") && !line.contains("// Generated by Selenium IDE")
								&& !line.contains("// Test ") && !line.contains("// Step #")) {

							line = line + " ";
							String[] list = line.split("\\|");

							List<String> ListString = new ArrayList<String>();
							Collections.addAll(ListString, list);
							if (!list[3].trim().equals("")) {
								// System.out.println(line);
								// System.out.println(list.length);
								objStepObject = new StepObject();
								// objStepObject.setSno(list[0].replace("//", ""));
								objStepObject.setSno(stepNum.toString());
								objStepObject.setDescription(list[1]);
								objStepObject.setTestdata(list[3]);
								// if(list[4].equalsIgnoreCase(""))
								objStepObject.setConditions(list[4]);
								objStepObjectList.add(objStepObject);
//								for (int i = 0; i < list.length; i++) {
//									System.out.println(list[i]);
//								}

								stepNum++;
							}

						}

						// sb.append("\n"); // line feed

					}

					fr.close(); // closes the stream and release the resources

					String[] outputfilename = file.getName().split("\\.");
					String outputFilename = outputFolder + outputfilename[0] + ".txt";
					writeSteps(objStepObjectList, outputFilename);
					System.out.println("GENERATED TEST CASES FOR " + outputFilename);
					System.out.println();

				}
			}

		} catch (IOException e) {
			e.printStackTrace();
		}
		System.out.println("============================================================================");
	}

	private static void writeSteps(ArrayList<StepObject> objStepObjectList, String filename) {

		try {
			FileWriter testcasescript = new FileWriter(filename);
			for (StepObject stepObject : objStepObjectList) {

				testcasescript.write(stepObject.getSno());
				testcasescript.write("		");
				testcasescript.write(stepObject.getDescription());
				testcasescript.write("		");
				testcasescript.write(stepObject.getTestdata());
				testcasescript.write("		");
				testcasescript.write(stepObject.getConditions());
				testcasescript.write("		");
				testcasescript.write("\n");
			}

			testcasescript.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

}
